name: Build simple test for windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86]

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1

    # - name: Add msbuild to PATH
    #   uses: microsoft/setup-msbuild@v1.0.1

    - name: Compile on ${{ matrix.architecture }}
      shell: bash
      run: |
        cl -I. main.c
        ls -la
        main.exe
